### PR TITLE
[MGDSTRM-10719] Adjust bundle script for kas-fleetshard bundle module

### LINKED ISSUE #237: Support podman in operators/generate-kas-fleetshard-olm-bundle.sh
Add an option to the script to run without docker when generating custom kas fleetshard image. This would avoid having to obtain docker license.

https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/blob/main/operators/generate-kas-fleetshard-olm-bundle.sh#L351

### PR DESCRIPTION
**Pull request by MikeEdgar**
- Bumps kas-fleetshard to v1.0.18 (operator version 0.34.0)
- Incorporates changes from https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/pull/247
- Fixes https://github.com/bf2fc6cc711aee1a0c2a/kas-installer/issues/237

Depends on merge of https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard/pull/871

### CODE REVIEW

**Comment by biswassri** [comment]
@MikeEdgar One small change, can we also include the change for situation where `${USER}` isn't same as `Quay Username` in the `generate-olm-bundle` script?

**Comment by MikeEdgar** [comment]
That would be done by using the `--image-group` argument. Or do you mean something else?

**Comment by biswassri** [comment]
> That would be done by using the `--image-group` argument. Or do you mean something else?

Oh sorry! I forgot that option. Everything else works fine for me.

**Review by biswassri — APPROVED** [review]
LGTM

**Pull request merged**
